.\" Manpage for renderer.
.\" Contact Tibor Bödecs to correct errors or typos.

.TH man 1 "6th October, 2017" "1.0.0" "renderer man page"
.SH NAME
renderer \- The only true way to toggle Xcode's markdown rendering feature.
.SH SYNOPSIS
renderer
.SH DESCRIPTION
The renderer tool will turn on or off markdown rendering in an Xcode project.
.SH OPTIONS
The iconer app has many options. You can supply:
.IP "-h, --help"
Displays help
.IP "-v, --version"
Log version information
.SH SEE ALSO
brew(1)
.SH BUGS
No known bugs. :)
.SH AUTHOR
Tibor Bodecs (mail.tib@gmail.com)